const header=document.querySelector('#header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30),{passive:true});
const menu=document.querySelector('#menu'),nav=document.querySelector('#nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const galleries={gralha:[['assets/gralha-web/01.webp','Hidromassagem com vista para a mata'],['assets/gralha-web/02.webp','Cama queen e enxoval'],['assets/gralha-web/05.webp','Portas de vidro para o deck'],['assets/gralha-web/06.webp','Deck privativo na mata'],['assets/gralha-web/07.webp','Ambiente amplo do chalé'],['assets/gralha-web/11.webp','Lareira de pedra'],['assets/gralha-web/12.webp','Banheiro'],['assets/gralha-web/14.webp','Rio nos fundos da propriedade'],['assets/gralha-web/15.webp','Fogueira entre as árvores'],['assets/gralha-web/16.webp','Espaço externo junto à mata']],tucano:[['assets/tucano-web/01.webp','Hidromassagem e janelas amplas'],['assets/tucano-web/03.webp','Visão completa do interior'],['assets/tucano-web/04.webp','Cama queen e mesa de café'],['assets/tucano-web/05.webp','Cama diante da parede de pedra'],['assets/tucano-web/08.webp','Lareira a lenha acesa'],['assets/tucano-web/09.webp','Hidromassagem junto às janelas'],['assets/tucano-web/12.webp','Área de banho e bancada'],['assets/tucano-web/15.webp','Bancada com vista para a mata'],['assets/tucano-web/20.webp','Varanda com cobertura de vidro'],['assets/tucano-web/21.webp','Varanda e jardim'],['assets/tucano-web/22.webp','Deck do chalé'],['assets/tucano-web/23.webp','Jardim da propriedade']]};
const dialog=document.querySelector('#galleryDialog'),photo=dialog.querySelector('img'),caption=dialog.querySelector('figcaption');let current=[],index=0;function show(i){index=(i+current.length)%current.length;[photo.src,caption.textContent]=current[index];photo.alt=caption.textContent}function openGallery(name,start=0){current=galleries[name];show(start);dialog.showModal();document.body.style.overflow='hidden'}document.querySelectorAll('.open-gallery').forEach(b=>b.addEventListener('click',()=>openGallery(b.dataset.gallery)));document.querySelectorAll('.lodge-strip').forEach(strip=>strip.querySelectorAll('button').forEach((b,i)=>b.addEventListener('click',()=>openGallery(strip.dataset.gallery,i+1))));dialog.querySelector('.gallery-close').addEventListener('click',()=>dialog.close());dialog.querySelector('.gallery-prev').addEventListener('click',()=>show(index-1));dialog.querySelector('.gallery-next').addEventListener('click',()=>show(index+1));dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});addEventListener('keydown',e=>{if(!dialog.open)return;if(e.key==='ArrowLeft')show(index-1);if(e.key==='ArrowRight')show(index+1)});

const waterfallImages=[...document.querySelectorAll('.waterfall-gallery>img')],waterfallDots=[...document.querySelectorAll('.photo-dots button')];let waterfallIndex=0;function showWaterfall(i){waterfallIndex=(i+waterfallImages.length)%waterfallImages.length;waterfallImages.forEach((img,n)=>img.classList.toggle('active',n===waterfallIndex));waterfallDots.forEach((dot,n)=>dot.classList.toggle('active',n===waterfallIndex))}waterfallDots.forEach((dot,i)=>dot.addEventListener('click',()=>showWaterfall(i)));if(waterfallImages.length)setInterval(()=>showWaterfall(waterfallIndex+1),5200);

const reviewHighlights=[
['Hospitalidade em cada detalhe da estadia.','Hospitalidade · citada 95 vezes nos dois anúncios'],
['Um café da manhã que vira parte da experiência.','Café da manhã · citado 64 vezes'],
['Conforto pensado para realmente desacelerar.','Conforto · citado 32 vezes'],
['Limpeza impecável do início ao fim.','Limpeza · citada 34 vezes'],
['Natureza e água corrente como trilha sonora.','Rio · citado 10 vezes'],
['Espaços ao ar livre para aproveitar sem pressa.','Área externa · citada 19 vezes'],
['Uma localização especial, perto das cachoeiras.','Localização · citada 17 vezes no Chalé Gralha'],
['Silêncio e aconchego para noites restauradoras.','Qualidade do sono · citada 15 vezes'],
['Ambientes que surpreendem tanto quanto as fotos.','Espaço interno · citado 21 vezes'],
['Cuidado, beleza e acolhimento em uma só experiência.','Síntese dos destaques verificados no Airbnb']
];
const reviewText=document.querySelector('#review-text'),reviewMeta=document.querySelector('#review-meta'),reviewProgress=document.querySelector('.review-progress');let reviewIndex=0,reviewTimer;function showReview(i){reviewIndex=(i+reviewHighlights.length)%reviewHighlights.length;reviewText.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:450,easing:'ease-out'});reviewText.textContent=reviewHighlights[reviewIndex][0];reviewMeta.textContent=reviewHighlights[reviewIndex][1];reviewProgress.style.background=`linear-gradient(90deg,var(--gold) 0 ${(reviewIndex+1)*10}%,rgba(201,164,92,.18) ${(reviewIndex+1)*10}%)`}function startReviews(){clearInterval(reviewTimer);reviewTimer=setInterval(()=>showReview(reviewIndex+1),5500)}document.querySelector('.review-prev')?.addEventListener('click',()=>{showReview(reviewIndex-1);startReviews()});document.querySelector('.review-next')?.addEventListener('click',()=>{showReview(reviewIndex+1);startReviews()});if(reviewText)startReviews();
